services:
  api:
    container_name: evolution_api
    restart: always
    image: atendai/evolution-api:latest
    depends_on:
      - redis
      - postgres
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 8080

  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis
    restart: always
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    restart: always
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000", "-c", "listen_addresses=*"]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tamilivalle
      - POSTGRES_PASSWORD=tami0706
      - POSTGRES_DB=evolution
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    depends_on:
      - api
    ports:
      - "5678:5678"
    networks:
      - evolution-net
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=N8!Tami22
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=evolution
      - DB_POSTGRESDB_USER=tamilivalle
      - DB_POSTGRESDB_PASSWORD=tami0706
      - QUEUE_MODE=redis
      - QUEUE_REDIS_HOST=redis
      - WEBHOOK_TUNNEL_URL=http://54.232.23.18:5678
      - N8N_HOST=54.232.23.18
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - TZ=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:
  n8n_data:


networks:
  evolution-net:
    name: evolution-net
    driver: bridge
